name: dbans-telegram-addon
description: ${project.description}
version: '${version}'

main: de.silke.dbans.telegram.Main
api-version: '1.21'
load: POSTWORLD

authors: [ Silke ]
website: github.com/blackysky

depend: [ dBans ]
