name: dbans-telegram-addon
description: ${project.description}
version: '${version}'

main: de.silke.dbans.telegram.Main
api-version: '1.21'
load: POSTWORLD

authors: [ Silke ]
website: github.com/blackysky

depend: [ dBans ]

commands:
  dbanstelegram:
    description: Manage the dBans Telegram addon
    usage: /<command> <reload|test>
    permission: dbanstelegram.reload
    permission-message: You don't have permission to do that.
